apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
spec:
 rules:
 - http:
     paths:
     - path: /
       backend:
         serviceName: server
         servicePort: 8080
