apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 8080
  type: ClusterIP
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        ports:
        - containerPort: 8080